# Generated by Django 5.1 on 2024-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpi_drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
